### ISSUE TITLE
Examples highly appreciated

### ISSUE THREAD

**Issue by denyago** [Shougo/ddc-filter-converter_remove_overlap#1]
I'm trying to add DDC to my Vim, and I am curious about the use of this converter.

It's not clear from the documentation how it differs from https://github.com/Shougo/ddc-sorter_rank, as the docs text contains the same comment:
- [this plugin](https://github.com/Shougo/ddc-converter_remove_overlap/blob/main/doc/ddc-converter_remove_overlap.txt#L17)
- [ddc-sorter_rank](https://github.com/Shougo/ddc-sorter_rank/blob/main/doc/ddc-sorter_rank.txt#L17)

As for the source file, I'm a bit lazy to go through the source code. 😅

**Comment by Shougo** [comment]
For example if you want to complete "foobar" before "bar", only "foo" is
inserted.  Because "bar" is already inserted in the text.

**Comment by denyago** [comment]
Thank you!
